language: haskell

before_install:
  - cd groundhog-test
  - psql -f init_postgresql.sql -U postgres
  - mysql -u root < init_mysql.sql

install:
  - cabal install --force-reinstalls --enable-tests -fsqlite -fpostgresql -fmysql

after_failure: cat dist/test/*.log
